# Generated by Django 4.0.4 on 2022-04-19 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('boss_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Начальник',
                'verbose_name_plural': 'Начальники',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('pos_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pos_name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('salary', models.IntegerField()),
                ('hire_date', models.DateField()),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.boss')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.position')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.AddField(
            model_name='boss',
            name='boss_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.position'),
        ),
        migrations.AddField(
            model_name='boss',
            name='subordinates',
            field=models.ManyToManyField(related_name='bosses', to='main.position'),
        ),
    ]
