# Generated by Django 3.2.8 on 2022-05-03 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_position_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='boss',
        ),
        migrations.DeleteModel(
            name='Boss',
        ),
    ]
